dreamers_mas/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'mas'
urlpatterns = [
    path('', views.dashboard, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('profile/chang-password/', views.profile_change_pass, name='profile_change_pass'),
    path('profile/check-old-password/', views.check_old_pass, name='check_old_pass'),
    path('profile/update-infor/', views.profile_update_infor, name='profile_update_infor'),
    path('profile/check-phone/', views.check_phone, name='check_phone'),

    path('noti/', views.load_unread_mail, name='load_unread_mail'),


    path('report/', include('report.urls')),
    path('campaign/', include('campaign.urls')),
    path('support/', include('support.urls')),
    path('payment/', include('payment.urls')),
]

dreamers_mas/dreamers_mas/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('mas/', include('dashboard.urls')),
    path('', include('homepage.urls')),
    path('administrator/', include('admin_dashboard.urls')),
    # path('error/', i),
]

handler404 = 'homepage.views.error404'
handler500 = 'homepage.views.error500'

dreamers_mas/homepage/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
    path('payment/', include('payment.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cpanel/',views.cpanel, name='cpanel'),
    path('login/check-login', views.check_login, name='check_login'),
    path('register/check-email', views.check_email, name='check_email'),
    path('register/check-password', views.check_password, name='check_password'),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.change_password_success, name='change_password'),
    path('login/change-password', views.change_password, name='pass_change'),
    path('login/confirm-password', views.confirm_change_pass, name='confirm_change_pass'),
    # path('login/check-pass-change', views.check_password_change, name='check_pass_change'),


    # url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    # path('connection/',views.formView, name='loginForm')
]

dreamers_mas/report/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<cam_id>/', views.report, name='report'),
]

dreamers_mas/dashboard/models.py
from dreamers_mas.models import *
import logging


def get_info_of_user(user):
    try:
        return user.info.all()[0]
    except Exception as e:
        logging.getLogger("error_logger").error("get_info_of_user: " + repr(e))
        return None


def get_messages_unread_of_user(username):
    try:
        query = "match(u:User{username:'" + username + "'})--(cs:ChatSubject)--(cm:ChatMessage) " \
                                                       "where cm.read = false and u.username = cm.receiver_username" \
                                                       " return cm order by cm.send_date desc"
        results, meta = db.cypher_query(query)
        return [ChatMessage.inflate(row[0]) for row in results]
    except Exception as e:
        logging.getLogger("error_logger").error("get_all_subjects: " + repr(e))
        return None


def get_sub_id_by_mess_id(mess_id):
    try:
        query = "match(cm:ChatMessage{mess_id:'" + mess_id + "'})--(cs:ChatSubject) return cs.sub_id"
        results, meta = db.cypher_query(query)
        return results[0][0]
    except Exception as e:
        logging.getLogger("error_logger").error("get_all_subjects: " + repr(e))
        return None


def cal_total_revenue(uid):
    try:
        query = "match(u:User{uid:'" + uid + "'})--(c:Campaign)--" \
                     "(con:Consumer)-[r:BUYS]->(clo:Clothes) with r.quantity*r.price as re return sum(re)"
        results, meta = db.cypher_query(query)
        count = results[0][0]
        if count is None:
            return 0
        return count
    except Exception as e:
        logging.getLogger("error_logger").error("cal_total_revenue: " + repr(e))
        return 0


def get_total_sales(uid):
    try:
        query = "match(u:User{uid:'" + uid + "'})--(c:Campaign)--(con:Consumer)-[r:BUYS]->" \
                                             "(clo:Clothes) return sum(r.quantity)"
        results, meta = db.cypher_query(query)
        count = results[0][0]
        if count is None:
            return 0
        return count
    except Exception as e:
        logging.getLogger("error_logger").error("get_total_sales: " + repr(e))
        return 0


def get_average_all_recall(uid):
    try:
        query = "match(u:User{uid:'" + uid + "'})--(c:Campaign)--(r:Report) return avg(r.recall)"
        results, meta = db.cypher_query(query)
        avg = results[0][0]
        if avg is None:
            return 0
        return avg
    except Exception as e:
        logging.getLogger("error_logger").error("get_average_all_recall: " + repr(e))
        return 0


def get_average_all_precision(uid):
    try:
        query = "match(u:User{uid:'" + uid + "'})--(c:Campaign)--(r:Report) return avg(r.precision)"
        results, meta = db.cypher_query(query)
        avg = results[0][0]
        if avg is None:
            return 0
        return avg
    except Exception as e:
        logging.getLogger("error_logger").error("get_average_all_precision: " + repr(e))
        return 0


def cal_all_reports(uid):
    try:
        query = "match(u:User{uid:'" + uid + "'})--(c:Campaign)--(r:Report)" \
                                             " return r order by r.create_date desc"
        results, meta = db.cypher_query(query)
        reports = [Report.inflate(row[0]) for row in results]
        # count_day = 0
        count = 0
        report_data = {}
        if len(reports) == 0:
            return report_data
        create_date = reports[0].create_date.strftime("%Y-%m-%d")
        total_recommend = 0
        total_precision = 0
        total_recall = 0
        for r in reports:
            if r.create_date.strftime("%Y-%m-%d") == create_date:
                total_recommend += r.num_recommend
                total_precision += r.precision
                total_recall += r.recall
                count += 1
            else:
                report_data[create_date] = {
                    "total_recommend": total_recommend,
                    "avg_precision": total_precision/count,
                    "avg_recall": total_recall/count
                }
                total_recommend = r.num_recommend
                total_precision = r.precision
                total_recall = r.recall
                count = 1
                create_date = r.create_date.strftime("%Y-%m-%d")
            #     count_day += 1
            # if count_day > 15:
            #     break
        return report_data
    except Exception as e:
        logging.getLogger("error_logger").error("cal_all_reports: " + repr(e))
        return []


def get_sale_last_15days(uid):
    try:
        query = "match(u:User{uid:'" + uid + "'})--(c:Campaign)--" \
                                     "(con:Consumer)-[r:BUYS]->(clo:Clothes) return r order by r.purchase_time desc"
        results, meta = db.cypher_query(query)
        purs = [PurchaseHistory.inflate(row[0]) for row in results]
        count_day = 0
        sale_data = []
        sale_date = purs[0].purchase_time.strftime("%Y-%m-%d")
        num_sales = 0
        for p in purs:
            if p.purchase_time.strftime("%Y-%m-%d") == sale_date:
                num_sales += p.quantity
            else:
                sale_data.insert(0, {
                    "sale_date": sale_date,
                    "num_sales": num_sales
                })
                # sale_data[sale_date] = num_sales
                sale_date = p.purchase_time.strftime("%Y-%m-%d")
                num_sales = p.quantity
                count_day += 1
            if count_day > 15:
                break
        return sale_data
    except Exception as e:
        # logging.getLogger("error_logger").error("get_sale_last_15days: " + repr(e))
        return {}

dreamers_mas/dashboard/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from campaign.models import get_last_payment_of_user, get_all_campaigns_of_user
from homepage.views import validation
from .models import *
from dreamers_mas.decorators import user_login_required
from homepage.models import get_user_by_uid, logging
from .models import *


# Create your views here.
@user_login_required
def dashboard(request):
    try:
        check_expire(request)
        context = check_noti(request)

        uid = request.session['uid']
        user = get_user_by_uid(uid)

        total_revenue = cal_total_revenue(uid)
        context["total_revenue"] = total_revenue

        total_sales = get_total_sales(uid)
        context["total_sales"] = total_sales

        avg_all_recall = get_average_all_recall(uid)
        context["avg_all_recall"] = avg_all_recall*100

        avg_all_precision = get_average_all_precision(uid)
        context["avg_all_precision"] = avg_all_precision*100

        dashboard_data = make_dashboard_chart_data(uid)
        context["dashboard_data"] = dashboard_data

        return render(request, 'dashboard.html', context)
    except Exception as e:
        logging.getLogger("error_logger").error("dashboard. " + repr(e))
        messages.error(request, "Can't show dashboard!")
        return render(request, 'dashboard.html')


def make_dashboard_chart_data(uid):
    report_data = cal_all_reports(uid)
    sale_data = get_sale_last_15days(uid)
    dashboard_data = []
    sale_date = ""
    for s in sale_data:
        sale_date = s["sale_date"]
        try:
            report = report_data[sale_date]
            if report is None:
                report = {
                    "total_recommend": 0,
                    "avg_precision": 0,
                    "avg_recall": 0
                }
        except Exception as e:
            report = {
                "total_recommend": 0,
                "avg_precision": 0,
                "avg_recall": 0
            }
            pass
        dashboard_data.append({
            "date": sale_date,
            "sale": s["num_sales"],
            "precision": round(report["avg_precision"]*100, 1),
            "recall": round(report["avg_recall"]*100, 1)
        })
    if len(report_data) > 0:
        next_date = (datetime.strptime(sale_date, '%Y-%m-%d') + timedelta(days=1)).strftime("%Y-%m-%d")
        dashboard_data.append({
            "date": next_date
        })

    return dashboard_data


@user_login_required
def load_unread_mail(request):
    try:
        if request.is_ajax():
            context = check_noti(request)
            return JsonResponse(context)
        else:
            return HttpResponseRedirect(reverse("mas:dashboard"))
    except Exception as e:
        logging.getLogger("error_logger").error("load_unread_mail. " + repr(e))


def check_noti(request):
    try:
        uid = request.session['uid']
        user = get_user_by_uid(uid)
        unread_mess = get_messages_unread_of_user(user.username)
        list_unread = []
        # only show 5 first unread email newest
        for mess in unread_mess:
            sub_id = get_sub_id_by_mess_id(mess.mess_id)
            list_unread.append({
                "mess": mess.dumps(),
                "sub_id": sub_id
            })

        context = {
            'list_unread': list_unread,
            'num_new': len(unread_mess),
        }
        return context

    except Exception as e:
        logging.getLogger("error_logger").error("check_noti. " + repr(e))
        messages.error(request, "Can't load mail!")


@user_login_required
def profile(request):
    try:
        uid = request.session['uid']
        user = get_user_by_uid(uid)
        info = get_info_of_user(user)
        if info.first_name is None:
            info.first_name = ""
        if info.last_name is None:
            info.last_name = ""
        if info.company_name is None:
            info.company_name = ""
        if info.phone is None:
            info.phone = ""
        context = {
            'user': user,
            'info': info,
        }
        check_expire(request)
        return render(request, 'profile.html', context)
    except Exception as e:
        logging.getLogger("error_logger").error("profile. " + repr(e))
        messages.error(request, "Can't show your profile!")
        return render(request, 'dashboard.html')


def check_expire(request):
    try:
        uid = request.session['uid']
        if uid is not None:
            user = get_user_by_uid(uid)
            pay = get_last_payment_of_user(user)
            expire = False
            if pay is not None:
                end = pay.end_date.strftime("%Y-%m-%d %H:%M")
                now = datetime.now().strftime("%Y-%m-%d %H:%M")
                remain_time = (datetime.strptime(end, "%Y-%m-%d %H:%M") -
                               datetime.strptime(now, "%Y-%m-%d %H:%M")).total_seconds()
                if remain_time < 0:
                    # disable payment
                    pay.status = 1
                    pay.save()

                    # disable all campaigns
                    cams = get_all_campaigns_of_user(user)
                    if cams is not None:
                        for cam in cams:
                            cam.status = 1
                            cam.save()

                    expire = True
            return expire
    except Exception as e:
        # logging.getLogger('error').error('check_expire', repr(e))
        return {}


def check_old_pass(request):
    data = {}
    if request.method == "GET":
        raise Http404("URL doesn't exists")
    else:
        uid = request.session['uid']
        if uid is not None:
            user = get_user_by_uid(uid)
            input_old_pass = request.POST.get('old_pass')
            if user is not None:
                if input_old_pass is None:
                    data['message'] = 'The old password must be filled'
                else:
                    if pbkdf2_sha256.verify(input_old_pass, user.password):
                        data['message'] = 'success'
                    else:
                        data['message'] = 'The Old Password is wrong!!'

            return JsonResponse(data)
        return HttpResponseRedirect(reverse('homepage:index'))


def profile_change_pass(request):
    if request.method == "GET":
        raise Http404("URL doesn't exists")
    else:
        uid = request.session['uid']
        if uid is not None:
            user = get_user_by_uid(uid)
            input_old_pass = request.POST.get('old_password')
            new_pass = request.POST.get('new_password')
            re_new_pass = request.POST.get('re_new_password')
            if user is not None:
                if pbkdf2_sha256.verify(input_old_pass, user.password) and new_pass == re_new_pass and \
                        validation.is_valid_password(new_pass):
                    user.password = new_pass
                    user.save()
                    messages.success(request, 'Change password success')
                    return HttpResponseRedirect(reverse('mas:profile'))
        else:
            return HttpResponseRedirect(reverse('homepage:index'))


def profile_update_infor(request):#Update profile
    if request.method == "GET":
        raise Http404("URL doesn't exists")
    else:
        uid = request.session['uid']
        if uid is not None:
            user = get_user_by_uid(uid)
            first_name = request.POST.get('first_name').strip()
            last_name = request.POST.get('last_name').strip()
            company_name = request.POST.get('company_name').strip()
            phone = request.POST.get('phone').strip()

            if user is not None:
                infor = get_info_of_user(user)
                infor.first_name = first_name
                infor.last_name = last_name
                infor.company_name = company_name
                if validation.is_valid_phone(phone):#validate Phonenumber
                    infor.phone = phone
                    infor.save()
                messages.success(request, 'Your information is updated')#popup message
                return HttpResponseRedirect(reverse('mas:profile'))
            else:
                return HttpResponseRedirect(reverse('homepage:index'))
        else:
            return HttpResponseRedirect(reverse('homepage:index'))

def check_phone(request):#check phone number to send to ajax
    data = {}
    if request.method == "GET":
        raise Http404("URL doesn't exists")
    else:
        uid = request.session['uid']
        if uid is not None:
            user = get_user_by_uid(uid)
            phone = request.POST.get('phone')
            if user is not None:
                if validation.is_valid_phone(phone):
                    data['message'] = 'success'
                else:
                    data['message'] = 'Phone number is invalid!'
                return JsonResponse(data)
        else:
            return HttpResponseRedirect(reverse('homepage:index'))

dreamers_mas/dashboard/templates/dashboard.html
{% extends "mas-base.html" %}

{% block title %}Dashboard - MAS{% endblock %}

{% load staticfiles %}
{% load humanize %}

{% block css %}
    {#    <link href="{% static 'css/lib/calendar2/semantic.ui.min.css' %}" rel="stylesheet"> #}
    <link href="{% static 'css/lib/calendar2/pignose.calendar.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/lib/amchart/export.css' %}" rel="stylesheet">

{% endblock %}

{% block cur_page_name %}Dashboard{% endblock %}

{% block path %}
    <li class="breadcrumb-item">Dashboard</li>
{% endblock %}

{% block content %}
    <script>
        $(document).ready(function () {
            var data = "{{dashboard_data}}".replace(/&#39;/g, "\"");
            var json = JSON.parse(data);
            load_dashboard_chart(json);
        });

    </script>

    <div class="row">
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-usd f-s-40 color-primary"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ total_revenue|floatformat:0|intcomma }}</h2>
                        <p class="m-b-0">Total Revenue</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-shopping-cart f-s-40 color-success"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ total_sales }}</h2>
                        <p class="m-b-0">Sales</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-refresh f-s-40 color-warning"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ avg_all_recall|floatformat:1 }} %</h2>
                        <p class="m-b-0">Recall Average</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-signal f-s-40 color-danger"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ avg_all_precision|floatformat:1 }} %</h2>
                        <p class="m-b-0">Precision Average</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row bg-white m-l-0 m-r-0 box-shadow ">

        <!-- column -->
        <div class="col-lg-8">
            <div class="card">
                <div class="card-title">
                    <h4>Overview last 15 days</h4>
                </div>
                <div class="card-body">
                    <div id="dashboard_chart"></div>
                </div>
            </div>
        </div>
        <!-- column -->

        <!-- column -->
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <div class="year-calendar"></div>
                </div>
            </div>
        </div>
        <!-- column -->
    </div>

{% endblock %}

{% block js %}
    <!-- Amchart -->
    <script src="{% static 'js/lib/morris-chart/raphael-min.js' %}"></script>
    <script src="{% static 'js/lib/morris-chart/morris.js' %}"></script>
    <script src="{% static 'js/lib/morris-chart/dashboard1-init.js' %}"></script>


    <script src="{% static 'js/lib/calendar-2/moment.latest.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/semantic.ui.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/prism.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/pignose.calendar.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/pignose.init.js' %}"></script>

    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>


    <!-- Amchart -->
    <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script src="{% static 'js/lib/chart-amchart/serial.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/export.min.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/light.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/ammap.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/worldLow.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/pie.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/amstock.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/amchart-init.js' %}"></script>
    <script src="{% static 'js/report_chart.js' %}"></script>
{% endblock %}

dreamers_mas/dashboard/templates/profile.html
{% extends "mas-base.html" %}

{% block title %} Profile - MAS{% endblock %}

{% load staticfiles %}
{% load mathfilters %}

{% block css %}
     <link href="{% static 'css/myCss.css' %}" rel="stylesheet" />
{% endblock %}

{% block cur_page_name %}Profile{% endblock %}

{% block path %}
    <li class="breadcrumb-item active">Profile</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-two">
                        <header>
                            <div class="avatar">
                                <img src="{% static 'images/users/client.jpg' %}" alt=""/>
                            </div>
                        </header>
                        <h3>Hello <strong>{{ info.first_name }} {{ info.last_name }}</strong></h3>
{#                        <div class="desc">#}
{#                            Lorem ipsum dolor sit amet, consectetur adipisicing elit et cupiditate deleniti.#}
{#                        </div>#}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6 col-md-12">
            <div class="card">
                <div class="card-title">
                    {#                    Update your profile#}
                </div>
                <div class="card-body">
                    <div class="col-10 mx-auto">
                        <form class="form-horizontal form-material" action="{% url 'mas:profile_update_infor' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="col-md-12">First Name</label>
                                <div class="col-md-12">
                                    <input name="first_name" type="text" placeholder=""
                                           class="form-control form-control-line"
                                           value="{{ info.first_name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">Last Name</label>
                                <div class="col-md-12">
                                    <input name="last_name" type="text" placeholder=""
                                           class="form-control form-control-line"
                                           value="{{ info.last_name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">Company Name</label>
                                <div class="col-md-12">
                                    <input name="company_name" type="text" placeholder=""
                                           class="form-control form-control-line"
                                           value="{{ info.company_name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="example-email" class="col-md-12">Email</label>
                                <div class="col-md-12">
                                    <input type="email" placeholder=""
                                           class="form-control form-control-line" name="email"
                                           id="example-email" disabled
                                           value="{{ info.email }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">Phone Number</label>
                                <div class="col-md-12">
                                    <input type="text" placeholder=""
                                           name="phone" class="form-control form-control-line"
                                           value="{{ info.phone }}" data-url="{% url 'mas:check_phone' %}"
                                           onkeyup="check_phone(this);return false" >
                                    {% csrf_token %}
                                </div>
                                <div id="pass_not"></div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <input class="btn btn-success" id="submit_signup" type="submit" value="Update Profile">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-12">
            <div class="card">
                <div class="card-title">
                    {#                    Change your password#}
                </div>
                <div class="card-body">
                    <div class="col-10 mx-auto">
                        <form class="form-horizontal form-material" action="{% url 'mas:profile_change_pass' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="col-md-12">Old Password</label>
                                <div class="col-md-12">
                                    <input name="old_password" type="password"
                                           class="form-control form-control-line" id="old_pass" onblur="check_old_pass(this);return false"
                                    data-url="{% url 'mas:check_old_pass' %}" onkeyup="clear_login(this)" required >
                                    {% csrf_token %}
                                </div>
                                <div id="error"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">New Password</label>
                                <div class="col-md-12">
                                    <input name="new_password" type="password" placeholder=""
                                           class="form-control form-control-line" id="new_pass" onkeyup="clear_pass(this)"
                                           onblur="check_pass(this);return false"
                                            data-url="{% url 'homepage:check_password' %}" required>
                                    {% csrf_token %}
                                </div>
                                 <div id="pass_wrong"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">Re-type New Password</label>
                                <div class="col-md-12">
                                    <input name="re_new_password" type="password" placeholder=""
                                           class="form-control form-control-line" id="re_new_pass" onkeyup="clear_match(this)" required>
                                </div>
                                <div id="not_match"></div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-12">
                                    <input class="btn btn-success" id="submit_signup" type="submit" value="Change Password">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script src="{% static 'js/myAjax.js' %}"></script>
{% endblock %}