dreamers_mas/campaign/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_campaign, name='list_campaign'),
    path('create-campaign/', views.go_create_campaign, name='go_create_campaign'),
    path('create-campaign/create/', views.create_campaign, name='create_campaign'),
    path('pause/<cam_id>/', views.pause_campaign, name='pause_campaign'),
    path('resume/<cam_id>/', views.resume_campaign, name='resume_campaign'),

    path('go-update/<cam_id>/', views.go_update_campaign, name='go_update_campaign'),
    path('update/<cam_id>/', views.update_campaign, name='update_campaign'),

    path('delete/<cam_id>/', views.delete_campaign, name='delete_campaign'),
    path('download-template/', views.download_template, name='download_template'),

    path('update-creating-campaign-data/', views.update_creating_campaign_data, name='update_creating_campaign_data'),

]

dreamers_mas/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'mas'
urlpatterns = [
    path('', views.dashboard, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('profile/chang-password/', views.profile_change_pass, name='profile_change_pass'),
    path('profile/check-old-password/', views.check_old_pass, name='check_old_pass'),
    path('profile/update-infor/', views.profile_update_infor, name='profile_update_infor'),
    path('profile/check-phone/', views.check_phone, name='check_phone'),

    path('noti/', views.load_unread_mail, name='load_unread_mail'),


    path('report/', include('report.urls')),
    path('campaign/', include('campaign.urls')),
    path('support/', include('support.urls')),
    path('payment/', include('payment.urls')),
]

dreamers_mas/dreamers_mas/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('mas/', include('dashboard.urls')),
    path('', include('homepage.urls')),
    path('administrator/', include('admin_dashboard.urls')),
    # path('error/', i),
]

handler404 = 'homepage.views.error404'
handler500 = 'homepage.views.error500'

dreamers_mas/report/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<cam_id>/', views.report, name='report'),
]

dreamers_mas/campaign/views.py
import os
import threading
from datetime import datetime
from json import JSONEncoder

from neomodel import OUTGOING, Traversal, db

from campaign.threads import *
from dashboard.views import check_expire
from dreamers_mas import settings
from dreamers_mas.decorators import user_login_required
from homepage.models import get_user_by_uid
from .models import *
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse
import logging, csv


@user_login_required
def list_campaign(request):
    check_expire(request)
    try:
        uid = request.session['uid']
        user = get_user_by_uid(uid)

        cams = get_all_campaigns_of_user(user)
        if check_remain_number_campaign(user) < 1:
            show_create_btn = False
        else:
            show_create_btn = True

        pay = get_last_payment_of_user(user)

        # check expire
        expire = True
        if pay is not None:
            end = pay.end_date.strftime("%Y-%m-%d %H:%M")
            now = datetime.now().strftime("%Y-%m-%d %H:%M")
            remain_time = (datetime.strptime(end, "%Y-%m-%d %H:%M") - datetime.strptime(now,
                                                                                        "%Y-%m-%d %H:%M")).total_seconds()
            if remain_time > 0:
                expire = False
        else:
            expire = True

        package = get_current_package_of_user(user)
        cams_data_show = []
        if cams is not None:
            for cam in cams:
                cams_data_show.append({
                    'cam': cam,
                    'num_cons': count_all_consumers_of_campaign(uid, cam.cam_id),
                    'num_clos': count_all_clothes_of_campaign(uid, cam.cam_id),
                    'num_purs': count_all_purchases_of_campaign(uid, cam.cam_id)
                })
        context = {
            'package': package,
            'expire': expire,
            'cams_data_show': cams_data_show,
            'show_create_btn': show_create_btn,
        }
        return render(request, 'manage-campaign.html', context)
    except Exception as e:
        logging.getLogger("error_logger").error("list_campaign. " + repr(e))
        messages.error(request, "Can't list campaigns!")
        return render(request, 'manage-campaign.html')


@user_login_required
def go_create_campaign(request):
    check_expire(request)
    return render(request, 'create-campaign.html')


def check_remain_number_campaign(user):
    # check max campaign then get current number of campaign
    list_cam = get_all_campaigns_of_user(user)
    if list_cam is not None:
        num_cam = len(list_cam)
    else:
        num_cam = 0

    # get package user used
    package = get_current_package_of_user(user)
    if package is None:
        pkg_max_cam = 0
    else:
        pkg_max_cam = package.max_campaign
    return pkg_max_cam - num_cam


def valid_csv_files(request, csv_files):
    try:
        file_dict = {}
        for csv_file in csv_files:  # check all files
            # print(csv_file.name)
            if not csv_file.name.endswith('.csv'):
                raise Exception('File ' + csv_file.name + ' is not CSV type !')
            # if file is too large, return
            if csv_file.multiple_chunks():
                raise Exception("Uploaded " + csv_file.name + " file is too big (%.2f MB)." % (
                    csv_file.size / (1000 * 1000),))

            file_dict[csv_file.name] = csv_file

        # check all file name
        try:
            if file_dict["consumers.csv"] and file_dict["products.csv"] and file_dict["purchase_histories.csv"] \
                    and len(file_dict) == 3:
                return file_dict
        except KeyError:
            raise Exception("3 file's name must be consumers.csv, products.csv, purchase_histories.csv !")
    except Exception as e:
        logging.getLogger("error_logger").error("valid_csv_files. " + repr(e))
        raise


# @user_login_required
def update_creating_campaign_data(request):
    try:
        if request.is_ajax():
            uid = request.session['uid']
            user = get_user_by_uid(uid)

            context = {
                'live': False
            }

            for th in creating_campaign_threads:
                # get campaign is creating
                if th.is_alive():
                    if th.user.uid == uid and th.campaign.status == 2:
                        cam_id = th.campaign.cam_id
                        package = get_current_package_of_user(user)
                        context = {
                            'live': True,
                            'num_cons': count_all_consumers_of_campaign(uid, cam_id),
                            'num_clos': count_all_clothes_of_campaign(uid, cam_id),
                            'num_purs': count_all_purchases_of_campaign(uid, cam_id),
                            'num_cons_max': package.max_consumer,
                            'num_clos_max': package.max_clothes,
                            'num_purs_max': package.max_purchase_history
                        }
                        break
            return JsonResponse(context)
        else:
            return HttpResponseRedirect(reverse("mas:list_campaign"))
    except Exception as e:
        logging.getLogger("error_logger").error("update_creating_campaign_data. " + repr(e))
        return HttpResponseRedirect(reverse('mas:list_campaign'))


creating_campaign_threads = []

@user_login_required
# @db.transaction
def create_campaign(request):
    global creating_campaign_threads
    check_expire(request)
    uid = request.session['uid']
    user = get_user_by_uid(uid)
    try:

        if count_number_campaign_creating(uid) > 0:
            messages.warning(request, "Your are creating a campaign, let's wait to it's completed!")
            raise Exception("You can't create many campaign at the one times!")

        if check_remain_number_campaign(user) < 1:
            messages.warning(request, "You have created maximum number of campaign !")
            raise Exception("Number of campaign was maximum !")

        # Only proceed with method POST
        if request.method == "POST":
            try:
                # csv = request.FILES["csv_file"]  # get 1 file
                csv_files = request.FILES.getlist("csv_file")  # get file list
                file_dict = valid_csv_files(request, csv_files)
                cam_name = request.POST.get('cam_name').strip()

                if not check_campaign_name(request, user, cam_name):
                    return HttpResponseRedirect(reverse("mas:go_create_campaign"))

                # get payment to take end date
                pay = get_last_payment_of_user(user)

                cam = Campaign(
                    cam_id=generate_cam_id(user.uid),
                    cam_name=cam_name,
                    start_date=datetime.now(),
                    end_date=pay.end_date,
                    status=2
                ).save()

                # get package user used
                package = get_current_package_of_user(user)

                new_doc = None
                try:
                    new_doc = CreateCampaignFiles(
                        con_file=file_dict["consumers.csv"],
                        clo_file=file_dict["products.csv"],
                        pur_file=file_dict["purchase_histories.csv"],
                    )
                    new_doc.save()
                except Exception as e:
                    pass
                # create consumers, clothes and connect campaign to
                create_cam_thread = UpdateCampaignThread(request, uid + "" + cam.cam_id, user, cam, new_doc)
                create_cam_thread.start()
                creating_campaign_threads.append(create_cam_thread)

                # connect campaign to user, package, channel
                user.campaign.connect(cam)
                cam.pid.connect(package)

                # travel all channels of package to campaign connect to
                definition = dict(
                    node_class=Channel,
                    direction=OUTGOING,
                    relation_type=None,
                    model=None
                )
                relations_channel_traversal = Traversal(package, Channel.__label__, definition)
                all_channel_relations = relations_channel_traversal.all()
                for channel in all_channel_relations:
                    cam.channel_id.connect(channel)
                cam.save()

                messages.success(request, "Campaign \' " + cam.cam_name + " \' is creating!")

            except Exception as e:
                logging.getLogger("error_logger").error("Unable to upload file. " + repr(e))
                messages.error(request, "Unable to upload file.")
                return HttpResponseRedirect(reverse("mas:go_create_campaign"))
            return HttpResponseRedirect(reverse("mas:list_campaign"))
        else:
            return render(request, "create-campaign.html")
    except Exception as e:
        logging.getLogger("error_logger").error("create_campaign " + repr(e))
        messages.error(request, "Can't create campaign!")
        return HttpResponseRedirect(reverse("mas:list_campaign"))


@user_login_required
def pause_campaign(request, cam_id):
    check_expire(request)
    if request.method == "GET":
        uid = request.session['uid']
        cam = get_campaign_of_user(cam_id, uid)
        if cam is not None and cam.status == 0:
            cam.status = 1  # 1 is disable
            cam.save()
            messages.success(request, 'Paused campaign \'' + cam.cam_name + '\'!')
    return HttpResponseRedirect(reverse("mas:list_campaign"))


@user_login_required
@db.transaction
def resume_campaign(request, cam_id):
    check_expire(request)
    if request.method == "GET":

dreamers_mas/campaign/templates/create-campaign.html
{% extends "mas-base.html" %}

{% block title %}Create Campaign - MAS{% endblock %}

{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/lib/dropzone/dropzone.css' %}" rel="stylesheet">
    <!-- this css make error footer -->
    {#    <link href="{% static 'css/lib/calendar2/semantic.ui.min.css' %}" rel="stylesheet">#}
    <link href="{% static 'css/lib/sweetalert/sweetalert.css' %}" rel="stylesheet">

    <link href="{% static 'css/lib/calendar2/pignose.calendar.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet"/>
{% endblock %}

{% block cur_page_name %}Create Campaign{% endblock %}

{% block path %}
    <li class="breadcrumb-item active"><a href="{% url 'mas:list_campaign' %}">Campaign</a></li>
    <li class="breadcrumb-item">Create</li>
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card ">
                <div class="col-11 create-cam-form m-t-15">
                    <h4 class="card-title">Create Campaign</h4>
                    <h6 class="card-subtitle"></h6>
                    <h6 class="card-subtitle">For file upload put or drop <code>files</code> to form below, and <code>5 first
                        rows</code> will be showed.</h6>
                    <h6 class="card-subtitle">If you have not downloaded the templates, please download or update new template here:
                        <a href="{% url 'mas:download_template'  %}" download style="color: red"><code>templates.v1.0.zip</code></a>
                    </h6>
                    <form action="{% url "mas:create_campaign" %}" method="POST" enctype="multipart/form-data"
                          id="create_cam_form" onsubmit="return uploadCSV()">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-3 div-upfile" id="divupfile">
                                <input type="file" name="csv_file" id="csvFileUpload" class="upfile"
                                       accept=".csv" multiple="multiple" onchange="uploadCSV()">
                                <span class="span-upfile" id="spanfile">Choose files...</span>
                                <button type="button" class="btn btn-primary btn-xs" id="btnClearFiles"
                                        onclick="clearSelected();">Clear Files
                                </button>
                            </div>
                            <div class="col-9 form-horizontal">
                                <div class="form-group">
                                    <div class="fallback col-md-12 p-l-0">
                                        <input type="text" placeholder="Campaign's name" name="cam_name"
                                               class="form-control input-rounded" required>
                                    </div>
                                </div>
                                <div class="button-list">
                                    <button type="button" class="btn btn-warning"
                                            onclick="location.href='{% url 'mas:list_campaign' %}'">Cancel
                                    </button>
                                    <button type="submit" class="btn btn-success">Create</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row d-none" id="row_consumers">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Preview Consumers</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" id="tableConsumers">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Age</th>
                                <th>Gender</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Facebook</th>
                                <th>Zalo</th>
                                <th>Address</th>
                            </tr>
                            </thead>
                            <tbody id="tbodyConsumers">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row d-none" id="row_products">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Preview Products</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" id="tableProducts">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Age Range</th>
                                <th>Season</th>
                                <th>Material</th>
                                <th>Color</th>
                                <th>Price</th>
                                <th>Style</th>
                                <th>Gender</th>
                                <th>Brand</th>
                                <th>Clothes Type</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody id="tbodyProducts">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row d-none" id="row_purchases">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Preview Purchases</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" id="tablePurchases">
                            <thead>
                            <tr>
                                <th>Consumer ID</th>
                                <th>Clothes ID</th>
                                <th>Purchase Time</th>
                                <th>Quantity</th>
                                <th>Price</th>
                            </tr>
                            </thead>
                            <tbody id="tbodyPurchases">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <!-- Amchart -->
    <script src="{% static 'js/lib/morris-chart/raphael-min.js' %}"></script>
    <script src="{% static 'js/lib/morris-chart/morris.js' %}"></script>
    <script src="{% static 'js/lib/morris-chart/dashboard1-init.js' %}"></script>


    <script src="{% static 'js/lib/calendar-2/moment.latest.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/semantic.ui.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/prism.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/pignose.calendar.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/pignose.init.js' %}"></script>

    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>

    <script src="{% static 'js/lib/sweetalert/sweetalert.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/sweetalert/sweetalert.init.js' %}"></script>

    <!--Custom JavaScript -->
    <script src="{% static 'js/lib/dropzone/dropzone.js' %}"></script>

    <script src="{% static 'js/lib/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/datatables-init.js' %}"></script>
{% endblock %}

dreamers_mas/campaign/templates/recommendation_email_template.html
{% autoescape off %}
    Xin chào {{ consumer.name }},

    Đến lúc làm mới tủ đồ của mình rồi đấy!
    Thời gian gần đây có rất nhiều sản phẩm mới đã lên kệ ở {{ info.company_name }}. Nếu bạn đang phân vân với quá nhiều lựa chọn thì chúng tôi nghĩ rằng sản phẩm dưới đây sẽ phù hợp với bạn:

    Tên: {{ clothes.name }}
    Hãng: {{ clothes.brand }}
    Giá: {{ clothes.price }} vnđ
    Màu: {{ clothes.color }}
    Kiểu: {{ style }}

    Nếu bạn quan tâm, hãy liên hệ với {{ info.company_name }} để được phục vụ tốt nhất nhé!

    Thông tin liên hệ của {{ info.company_name }}:
        Điện thoại: 0{{ info.phone }}
        Email: {{ info.email }}

    Hẹn gặp lại {{ consumer.name }} trong ngày gần nhất <3


{% endautoescape %}