dreamers_mas/admin_dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'admin'
urlpatterns = [
    path('', views.admin_dashboard, name='index'),
    path('dashboard/', views.admin_dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('all-payment-history/', views.all_payment_history, name='all_payment_history'),

    # path('manage-user/', views.admin_manage_user, name='manage_user'),
    # path('manage-user/change-status-to-deactivate/', views.change_user_status_to_deactivate, name='change_user_status_to_deactivate'),
    # path('manage-user/change-status-to-active/', views.change_user_status_to_active, name='change_user_status_to_active'),

    path('noti/', views.load_unread_mail, name='load_unread_mail'),

    path('support/', include('admin_support.urls')),
    path('manage-package/', include('manage_package.urls')),
    path('manage-user/', include('manage_user.urls')),

]

dreamers_mas/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'mas'
urlpatterns = [
    path('', views.dashboard, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('profile/chang-password/', views.profile_change_pass, name='profile_change_pass'),
    path('profile/check-old-password/', views.check_old_pass, name='check_old_pass'),
    path('profile/update-infor/', views.profile_update_infor, name='profile_update_infor'),
    path('profile/check-phone/', views.check_phone, name='check_phone'),

    path('noti/', views.load_unread_mail, name='load_unread_mail'),


    path('report/', include('report.urls')),
    path('campaign/', include('campaign.urls')),
    path('support/', include('support.urls')),
    path('payment/', include('payment.urls')),
]

dreamers_mas/dreamers_mas/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('mas/', include('dashboard.urls')),
    path('', include('homepage.urls')),
    path('administrator/', include('admin_dashboard.urls')),
    # path('error/', i),
]

handler404 = 'homepage.views.error404'
handler500 = 'homepage.views.error500'

dreamers_mas/homepage/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
    path('payment/', include('payment.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cpanel/',views.cpanel, name='cpanel'),
    path('login/check-login', views.check_login, name='check_login'),
    path('register/check-email', views.check_email, name='check_email'),
    path('register/check-password', views.check_password, name='check_password'),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.change_password_success, name='change_password'),
    path('login/change-password', views.change_password, name='pass_change'),
    path('login/confirm-password', views.confirm_change_pass, name='confirm_change_pass'),
    # path('login/check-pass-change', views.check_password_change, name='check_pass_change'),


    # url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    # path('connection/',views.formView, name='loginForm')
]

dreamers_mas/manage_user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.manage_user, name='manage_user'),
    # path('profile/', views.profile, name='profile'),
    path('', views.admin_manage_user, name='manage_user'),
    path('change-status-to-deactivate/', views.change_user_status_to_deactivate,
         name='change_user_status_to_deactivate'),
    path('change-status-to-active/', views.change_user_status_to_active,
         name='change_user_status_to_active'),
]

dreamers_mas/report/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<cam_id>/', views.report, name='report'),
]

dreamers_mas/admin_dashboard/models.py
from django.db import models

# Create your models here.
from dreamers_mas.models import *


def get_number_of_user():  # count number of user
    query = "match(u:User{is_active:true}) where u.user_type>0 return count(u)"
    results, meta = db.cypher_query(query)
    list_user = results[0]
    return list_user[0]


def get_number_of_pending_user():
    query = "match (n:User) where n.user_type= 2 return count(n)"
    results, meta = db.cypher_query(query)
    list_user = results[0]
    return list_user[0]


def get_number_of_campaign():
    query = "match (n:Campaign) return count(n)"
    results, meta = db.cypher_query(query)
    list_user = results[0]
    return list_user[0]


def get_total_revenue():
    revenue = 0
    query = "match(u:User)-[r:USES]->(p:Package) return r.price"
    results, meta = db.cypher_query(query)

    for total in results:
        revenue += total[0]

    return revenue


def count_all_trial_package():
    try:
        query = "match(u:User)-[r:USES]->(p:Package) where r.pid = 'PKG1' return count(r)"
        results, meta = db.cypher_query(query)
        count = results[0][0]
        if count is None:
            return 0
        return count
    except Exception as e:
        logging.getLogger("error_logger").error("count_all_trial_package: " + repr(e))
        return 0


def count_all_standard_package():
    try:
        query = "match(u:User)-[r:USES]->(p:Package) where r.pid = 'PKG2' return count(r)"
        results, meta = db.cypher_query(query)
        count = results[0][0]
        if count is None:
            return 0
        return count
    except Exception as e:
        logging.getLogger("error_logger").error("count_all_standard_package: " + repr(e))
        return 0


def count_all_premium_package():
    try:
        query = "match(u:User)-[r:USES]->(p:Package) where r.pid = 'PKG3' return count(r)"
        results, meta = db.cypher_query(query)
        count = results[0][0]
        if count is None:
            return 0
        return count
    except Exception as e:
        logging.getLogger("error_logger").error("count_all_premium_package: " + repr(e))
        return 0

dreamers_mas/admin_dashboard/views.py
import logging
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.http import Http404, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from admin_dashboard.models import *
from dashboard.models import get_info_of_user, Package
from dashboard.views import check_noti
from dreamers_mas.decorators import admin_login_required
from homepage.models import get_user_by_uid, get_all_user
from dreamers_mas.models import User
from payment.models import get_all_payments


@admin_login_required
def admin_dashboard(request):
    try:
        num_user = get_number_of_user()
        num_pending_user = get_number_of_pending_user()
        num_campaign = get_number_of_campaign()
        total_revenue = get_total_revenue()

        package_data = {
            "trial": count_all_trial_package(),
            "standard": count_all_standard_package(),
            "premium": count_all_premium_package(),
        }

        context = {
            'check_noti': check_noti(request),
            'num_user': num_user,
            'num_pending_user': num_pending_user,
            'num_campaign': num_campaign,
            'total_revenue': total_revenue,
            'package_data': package_data,
        }
        return render(request, 'admin-dashboard.html', context)
    except Exception as e:
        logging.getLogger("error_logger").error("admin_dashboard. " + repr(e))
        messages.error(request, "Can't show dashboard!")
    return render(request, 'admin-dashboard.html')


@admin_login_required
def profile(request):
    try:
        uid = request.session['uid']
        user = get_user_by_uid(uid)
        info = get_info_of_user(user)
        if info.first_name is None:
            info.first_name = ""
        if info.last_name is None:
            info.last_name = ""
        if info.company_name is None:
            info.company_name = ""
        if info.phone is None:
            info.phone = ""
        context = {
            'user': user,
            'info': info,
        }
        return render(request, 'admin-profile.html', context)
    except Exception as e:
        logging.getLogger("error_logger").error("profile. " + repr(e))
        messages.error(request, "Can't show your profile!")
        return render(request, 'admin-dashboard.html')

#
# @admin_login_required
# def admin_manage_user(request):
#     try:
#         user_infor = []
#         users = User.nodes.filter(user_type__gt=0)
#         for i in users:
#             info = get_info_of_user(i)
#             user_data = {
#                 'username': i,
#                 'infor': info,
#
#             }
#             user_infor.append(user_data)
#         context = {
#             'info': user_infor,
#         }
#         return render(request, 'admin-manage-user.html', context)
#     except Exception as e:
#         logging.getLogger("error_logger").error("manage user. " + repr(e))
#         messages.error(request, "Can't show your profile!")
#     return render(request, 'admin-dashboard.html')
#
#
# @admin_login_required
# def change_user_status_to_deactivate(request):
#     if request.method == "GET":
#         raise Http404("URL doesn't exists")
#     else:
#         data = {}
#         user_name = request.POST["user_name"]
#         is_active = request.POST["is_active"]
#
#         user = User.nodes.get(username=user_name)
#         if user is not None and is_active == 'false':
#             user.is_active = False
#             user.save()
#             data["message"] = "success"
#     return JsonResponse(data)
#
# @admin_login_required
# def change_user_status_to_active(request):
#     if request.method == "GET":
#         raise Http404("URL doesn't exists")
#     else:
#         data = {}
#         user_name = request.POST["user_name"]
#         is_active = request.POST["is_active"]
#
#         user = User.nodes.get(username=user_name)
#         if user is not None and is_active == 'true':
#             user.is_active = True
#             user.save()
#             data["message"] = "success"
#     return JsonResponse(data)


@admin_login_required
def load_unread_mail(request):
    try:
        if request.is_ajax():
            context = check_noti(request)
            return JsonResponse(context)
        else:
            return HttpResponseRedirect(reverse("admin:dashboard"))
    except Exception as e:
        logging.getLogger("error_logger").error("load_unread_mail. " + repr(e))



@admin_login_required
def all_payment_history(request):
    try:
        all_payments = get_all_payments()
        pay_table = []
        for pay in all_payments:
            pay_table.append({
                'payment': pay,
                'package': Package.nodes.filter(pid=pay.pid)[0],
            })

        context = {
            'pay_table': pay_table,
        }
        return render(request, 'admin-payment-history.html', context)
    except Exception as e:
        logging.getLogger("error_logger").error("all_payment_history. " + repr(e))
        messages.error(request, "Can't list payment!")
        return render(request, 'admin-payment-history.html')


# @admin_login_required
# def admin_dashboard(request):
#
#     num_user = get_number_of_user()
#     print(num_user)

dreamers_mas/admin_dashboard/templates/admin-dashboard.html
{% extends "admin-base.html" %}

{% block title %}Dashboard - MAS{% endblock %}

{% load staticfiles %}

{% block css %}
    {#    <link href="{% static 'css/lib/calendar2/semantic.ui.min.css' %}" rel="stylesheet"> #}
    <link href="{% static 'css/lib/calendar2/pignose.calendar.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet"/>
{% endblock %}

{% block cur_page_name %}Dashboard{% endblock %}

{% block path %}
    <li class="breadcrumb-item">Dashboard</li>
{% endblock %}

{% block content %}

     <script>
        $(document).ready(function () {
            var package_data = "{{package_data}}".replace(/&#39;/g, "\"");
            var package_json = JSON.parse(package_data);
            load_doughnut_chart(package_json);
        });

    </script>

    <div class="row">
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-usd f-s-40 color-primary"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ total_revenue }}</h2>
                        <p class="m-b-0">Total Revenue</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-shopping-cart f-s-40 color-success"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ num_campaign }}</h2>
                        <p class="m-b-0">Campaign</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-archive f-s-40 color-warning"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ num_pending_user }}</h2>
                        <p class="m-b-0">Pending Customer</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-30">
                <div class="media">
                    <div class="media-left meida media-middle">
                        <span><i class="fa fa-user f-s-40 color-danger"></i></span>
                    </div>
                    <div class="media-body media-text-right">
                        <h2>{{ num_user }}</h2>
                        <p class="m-b-0">Customer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row bg-white m-l-0 m-r-0 box-shadow ">

        <!-- column -->

        <!-- column -->
        {#        <div class="col-lg-8">#}
        {#            <div class="card">#}
        {#                <div class="card-title">#}
        {#                    <h4>AmChart</h4>#}
        {#                </div>#}
        {#                <div class="card-body">#}
        {#                    <div id="chartdiv3"></div>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}
        <div class="col-lg-6">
            <div class="card">
                <div class="card-title">
                    <h4>Package ratio</h4>
                </div>
                <div class="card-content">
                    <div id="package_chart" style="height: 400px"></div>
                </div>
            </div>
        </div>
        <!-- column -->

        <!-- column -->
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <div class="year-calendar"></div>
                </div>
            </div>
        </div>
        <!-- column -->
        <!-- column -->
    </div>

{% endblock %}

{% block js %}
    <!-- morris -->
    <script src="{% static 'js/lib/morris-chart/raphael-min.js' %}"></script>
    <script src="{% static 'js/lib/morris-chart/morris.js' %}"></script>
    <script src="{% static 'js/lib/morris-chart/dashboard1-init.js' %}"></script>


    <!-- Amchart -->
    <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script src="{% static 'js/lib/chart-amchart/serial.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/export.min.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/light.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/ammap.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/worldLow.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/pie.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/amstock.js' %}"></script>
    <script src="{% static 'js/lib/chart-amchart/amchart-init.js' %}"></script>
    <script src="{% static 'js/report_chart.js' %}"></script>


    <!-- Echart -->
    <script src="{% static 'js/lib/echart/echarts.js' %}"></script>
{#    <script src="{% static 'js/lib/echart/echarts-init.js' %}"></script>#}
    <script src="{% static 'js/dashboard_chart.js' %}"></script>


    <script src="{% static 'js/lib/calendar-2/moment.latest.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/semantic.ui.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/prism.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/pignose.calendar.min.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/calendar-2/pignose.init.js' %}"></script>

    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
{% endblock %}

dreamers_mas/admin_dashboard/templates/admin-manage-user.html
{#{% extends "admin-base.html" %}#}
{#{% block title %} Admin Manage user{% endblock %}#}
{#{% load staticfiles %}#}
{#{% load mathfilters %}#}
{##}
{#{% block css %}#}
{#     <link href="{% static 'css/myCss.css' %}" rel="stylesheet" />#}
{#    <link href="{% static 'css/lib/sweetalert/sweetalert.css' %}" rel="stylesheet">#}
{#{% endblock %}#}
{##}
{#{% block cur_page_name %}Manage User{% endblock %}#}
{#{% block path %}#}
{#    <li class="breadcrumb-item ">Manage User</li>#}
{#{% endblock %}#}
{#{% block content %}#}
{#                <!-- Start Page Content -->#}
{#                <div class="row">#}
{#                    <div class="col-12">#}
{#                        <div class="card">#}
{#                            <div class="card-body">#}
{#                                <h4 class="card-title">List User</h4>#}
{#                                <h6 class="card-subtitle">Data table example</h6>#}
{#                                <div class="table-responsive m-t-40">#}
{#                                    <table id="myTable" class="table table-bordered table-striped">#}
{#                                        <thead>#}
{#                                            <tr>#}
{#                                                <th>Username</th>#}
{#                                                <th>Full Name</th>#}
{#                                                <th>Company</th>#}
{#                                                <th>E-Mail</th>#}
{#                                                <th>Phone Number</th>#}
{#                                                <th>Status</th>#}
{#                                                <th>Action</th>#}
{##}
{#                                            </tr>#}
{#                                        </thead>#}
{#                                        <tbody>#}
{#                                        {% for user_infor in info %}#}
{#                                            <tr class="text-center">#}
{#                                                <td id="user_name">{{ user_infor.username.username }}</td>#}
{#                                                <td>{{ user_infor.infor.last_name }} {{ user_infor.infor.first_name }}</td>#}
{#                                                <td>{{ user_infor.infor.company_name }}</td>#}
{#                                                <td>{{ user_infor.infor.email }}</td>#}
{#                                                <td>{{ user_infor.infor.phone }}</td>#}
{#                                                {% if user_infor.username.user_type == 1 %}#}
{#                                                    <td id="td-active" class="text-center">#}
{#                                                    {% if user_infor.username.is_active is True %}#}
{#                                                        <a href="#">#}
{#                                                            <i class="fa fa-toggle-on tog-on"#}
{#                                                               id="deactivate"#}
{#                                                               data-url="{% url 'admin:change_user_status_to_deactivate' %}"#}
{#                                                               onclick="confirm_disable_user(this)"></i>#}
{#                                                        {% csrf_token %}#}
{#                                                        </a>#}
{#                                                        {% else %}#}
{#                                                        <a href="#">#}
{#                                                            <i class="fa fa-toggle-off tog-off"#}
{#                                                               id="active-user"#}
{#                                                               data-url="{% url 'admin:change_user_status_to_active' %}"#}
{#                                                               onclick="confirm_enable_user(this)"></i>#}
{#                                                        {% csrf_token %}#}
{#                                                        </a>#}
{#                                                    {% endif %}#}
{#                                                    </td>#}
{#                                                {% else %}#}
{#                                                    <td class="text-center"><button class="badge badge-warning" type="button" href="#" id="inactive">Pending</button></td>#}
{##}
{#                                                {% endif %}#}
{#                                            </tr>#}
{#                                        {% endfor %}#}
{##}
{##}
{#                                        </tbody>#}
{#                                    </table>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <!-- End PAge Content -->#}
{##}
{##}
{#{% endblock %}#}
{##}
{#{% block js %}#}
{#    <script src="{% static 'js/lib/datatables/datatables.min.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js' %}"></script>#}
{#    <script src="{% static 'js/lib/datatables/datatables-init.js' %}"></script>#}
{##}
{#    <script src="{% static 'js/lib/sweetalert/sweetalert.min.js' %}"></script>#}
{#    <!-- scripit init-->#}
{#    <script src="{% static 'js/lib/sweetalert/sweetalert.init.js' %}"></script>#}
{##}
{#    <script src="{% static 'js/myAjax.js' %}"></script>#}
{#{% endblock %}#}

dreamers_mas/admin_dashboard/templates/admin-profile.html
{% extends "admin-base.html" %}

{% block title %} Administrator Profile{% endblock %}

{% load staticfiles %}
{% load mathfilters %}

{% block css %}
    <link href="{% static 'css/myCss.css' %}" rel="stylesheet" />
{% endblock %}

{% block cur_page_name %}Profile{% endblock %}

{% block path %}
    <li class="breadcrumb-item ">Profile</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-two">
                        <header>
                            <div class="avatar">
                                <img src="{% static 'images/users/5.jpg' %}" alt=""/>
                            </div>
                        </header>
                        <h3>Hello <strong>{{ info.first_name }} {{ info.last_name }}</strong></h3>
                        <div class="desc">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-title">
                    {#                    Update your profile#}
                </div>
                <div class="card-body">
                    <div class="col-10 mx-auto">
                        <form class="form-horizontal form-material">
                            <div class="form-group">
                                <label class="col-md-12">First Name</label>
                                <div class="col-md-12">
                                    <input name="first_name" type="text" placeholder=""
                                           class="form-control form-control-line"
                                           value="{{ info.first_name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">Last Name</label>
                                <div class="col-md-12">
                                    <input name="last_name" type="text" placeholder=""
                                           class="form-control form-control-line"
                                           value="{{ info.last_name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="example-email" class="col-md-12">Email</label>
                                <div class="col-md-12">
                                    <input type="email" placeholder=""
                                           class="form-control form-control-line" name="email"
                                           id="example-email" disabled
                                           value="{{ info.email }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">Phone Number</label>
                                <div class="col-md-12">
                                    <input type="text" placeholder=""
                                           name="phone" class="form-control form-control-line"
                                           value="{{ info.phone }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="button-list">
                                    <button type="submit" class="btn btn-success m-l-15">Update Profile</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-12">
            <div class="card">
                <div class="card-title">
                    {#                    Change your password#}
                </div>
                <div class="card-body">
                    <div class="col-10 mx-auto">
                        <form class="form-horizontal form-material" action="{% url 'mas:profile_change_pass' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="col-md-12">Old Password</label>
                                <div class="col-md-12">
                                    <input name="old_password" type="password"
                                           class="form-control form-control-line" id="old_pass" onblur="check_old_pass(this);return false"
                                    data-url="{% url 'mas:check_old_pass' %}" onkeyup="clear_login(this)" required >
                                    {% csrf_token %}
                                </div>
                                <div id="error"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">New Password</label>
                                <div class="col-md-12">
                                    <input name="new_password" type="password" placeholder=""
                                           class="form-control form-control-line" id="new_pass" onkeyup="clear_pass(this)"
                                           onblur="check_pass(this);return false"
                                            data-url="{% url 'homepage:check_password' %}" required>
                                    {% csrf_token %}
                                </div>
                                 <div id="pass_wrong"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">Re-type New Password</label>
                                <div class="col-md-12">
                                    <input name="re_new_password" type="password" placeholder=""
                                           class="form-control form-control-line" id="re_new_pass" onkeyup="clear_match(this)" required>
                                </div>
                                <div id="not_match"></div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-12">
                                    <input class="btn btn-success" id="submit_signup" type="submit" value="Change Password">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/myAjax.js' %}"></script>
{% endblock %}