dreamers_mas/dreamers_mas/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('mas/', include('dashboard.urls')),
    path('', include('homepage.urls')),
    path('administrator/', include('admin_dashboard.urls')),
    # path('error/', i),
]

handler404 = 'homepage.views.error404'
handler500 = 'homepage.views.error500'

dreamers_mas/homepage/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
    path('payment/', include('payment.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cpanel/',views.cpanel, name='cpanel'),
    path('login/check-login', views.check_login, name='check_login'),
    path('register/check-email', views.check_email, name='check_email'),
    path('register/check-password', views.check_password, name='check_password'),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.change_password_success, name='change_password'),
    path('login/change-password', views.change_password, name='pass_change'),
    path('login/confirm-password', views.confirm_change_pass, name='confirm_change_pass'),
    # path('login/check-pass-change', views.check_password_change, name='check_pass_change'),


    # url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    # path('connection/',views.formView, name='loginForm')
]

dreamers_mas/report/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<cam_id>/', views.report, name='report'),
]

dreamers_mas/homepage/models.py
from django.db import models
from dreamers_mas.models import *


# Create your models here.

def exist_email(email):  # check Exist Email
    query = "Match(n:Information) return n.email"
    results, meta = db.cypher_query(query)
    for n in results:
        if email == n[0]:
            return False
    return True


def exist_username(username):  # Check Exist Email
    query = "Match(n:User) return n.username"
    results, meta = db.cypher_query(query)
    list_user = results
    for n in list_user:
        if username == n[0]:
            return False
    return True


def get_max_uid():  # Get UserID and return MAX_User_ID
    try:
        query = "match(n:User) return n.uid"
        results, meta = db.cypher_query(query)
        uid_number_list = []
        for n in results:
            x = (int(n[0][3:]))
            # print(x)
            uid_number_list.append(x)
        uid_number_list.sort()
        max_uid = uid_number_list[len(uid_number_list) - 1]
        return max_uid
    except Exception as e:
        logging.getLogger("error_logger").error("get_max_uid " + repr(e))
        return None


def get_user_by_username(username):
    try:
        query = "match(n:User{username:'" + username + "'}) return n"
        results, meta = db.cypher_query(query)
        return [User.inflate(row[0]) for row in results][0]
    except Exception as e:
        logging.getLogger("error_logger").error("get_user_by_username " + repr(e))
        return None


def get_user_by_uid(uid):
    try:
        user = User.nodes.get_or_none(uid=uid)
        return user
    except Exception as e:
        logging.getLogger("error_logger").error("get_user_by_uid " + repr(e))
        return None


def get_user_by_email(email):
    try:
        query = "match(n:User)--(m:Information{email:'" + email + "'}) return n"
        # query = "match(n:User{username:'" + username + "'}) return n"
        results, meta = db.cypher_query(query)
        return [User.inflate(row[0]) for row in results][0]
    except Exception as e:
        logging.getLogger("error_logger").error("get_user_by_username " + repr(e))
        return None


def get_all_user():  # get all use has type>0
    query = "match(n:User) where n.user_type >0 return n"
    results, meta = db.cypher_query(query)
    list_user = results[0]
    return list_user

dreamers_mas/homepage/views.py
import re

from django.contrib import messages

from dreamers_mas.decorators import *
import json
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.db.migrations import serializer
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, render_to_response
import base64, logging, re

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .models import *

# Code for load all data in homepage
from homepage.tokens import account_activation_token


def error404(request):
    return render(request, 'error_pages/page-error-404.html')


def error500(request):
    return render(request, 'error_pages/page-error-500.html')


def index(request):
    story = OurStory.nodes.all()
    our_service = OurService.nodes.all()
    imas = IMAS.nodes.all()
    contact = OurContact.nodes.all()
    all_packages = Package.nodes.order_by('current_price')
    data = {
        'story': story[0].description,
        'our_service': our_service,
        'imas': imas[0],
        'contact': contact[0],
        'all_packages': all_packages,
    }
    return render(request, 'index.html', data)


# # Code for validate password1 password2
# def check_pass(pass1, pass2):
#     if pass1 == pass2 and pass1:  # and pass1 de tranh viec nguoi dung nhap space
#         return pass2
#     raise Exception("Password and the confirm password doesn't match")
#
#
# # Code for validate username
# def check_username(username):
#     if not re.search(r'^\w+$', username):
#         raise Exception("username must be only character")
#     try:
#         User.nodes.get(username=username)
#     except ObjectDoesNotExist:
#         return username
#     raise Exception("Please try the other username!!")
#
#
# # Code for validate Email
# def check_email(email):
#     try:
#         Information.nodes.get(email=email)
#     except ObjectDoesNotExist
#         return email
#     raise Exception("This is Email already registered.")


# Save user to Neo4j
# def save():
#     User(username, password).save()


# auto create with max number of id code in database
def generate_uid():
    cur_uid = get_max_uid()
    if not cur_uid or cur_uid is None:  # init first UID
        new_uid = "USR0"
    else:
        # max_code = int(str(cur_uid)[3:])
        new_uid = "USR" + str(cur_uid + 1)  # Create
    return new_uid


class validation():  # Class to validate Input

    def is_valid_username(username):  # validating username

        if re.match("^[a-zA-Z0-9_.-]+$", str(username)) is not None:  # Username contains only character and number
            return True
            # return False
        else:
            return False
            # return True

    def is_valid_password(pass1):
        if re.match("^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,}",
                    # Password must contains at least 8 characters and UpperCase,LowerCase,Number,unique syntax
                    str(pass1)) is not None:
            return True
            # return False
        else:

            return False
            # return True

    def is_valid_email(email):  # Validating Email

        if re.match("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$", email) is not None and exist_email(
            str(email)) is True:
            return True
            # return False
        else:
            return False
            # return True

    def is_valid_phone(phone):  # Validating phone no
        if re.match("^(([0-9]|\\+)(\\d{9})|(\\d{11}))$", phone) is not None:
            return True
        else:
            return False

    def not_same_password(pass1, pass2):
        if pass1 == pass2:
            return True
        else:
            return False


# Code for register
def register(request):
    return_data = {}
    r_username = request.POST.get('username')
    r_email = request.POST.get('email')
    r_password1 = request.POST.get('password')
    r_password2 = request.POST.get('password2')
    r_uid = generate_uid()

    data = {
        'username': r_username,
        'password1': r_password1,
        'password2': r_password2,
        'email': r_email,

    }
    if validation.is_valid_username(r_username) and validation.is_valid_password(r_password1) and \
            validation.is_valid_email(r_email) and exist_username(r_username) and exist_email(r_email) is True:

        new_user = User(username=r_username, password=r_password1, uid=r_uid).save()
        # new_user.save()
        new_information = Information(email=r_email).save()
        # new_information.save()
        new_user.info.connect(new_information)

        print(new_user)
        print(new_information)
        current_site = get_current_site(request)
        message = render_to_string('acc_active_email.html', {
            'user': new_user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(new_user.uid)).decode,
            'token': account_activation_token.make_token(new_user),
        })
        # Sending activation link in terminal
        # user.email_user(subject, message)
        mail_subject = '<No-Reply> Verification E-mail'
        to_email = r_email
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.send()
        return_data["error_message"] = "Success"
        return render(request, 'after_register_page.html')
    # elif exist_username(r_username) is False:
    #     return HttpResponse("Username have been registered. Plz re-enter")
    elif exist_email(r_email) is False:
        return_data["error_message"] = "This Email have been Registered"
        JsonResponse(return_data)
        # return HttpResponse("This Email have been Registered. Try Agian!")
    elif validation.is_valid_username(r_username) is False:
        return_data["error_message"] = "Invalid username"
        JsonResponse(return_data)
        # return HttpResponse('Wrong userName')
    elif validation.is_valid_password(r_password1) is False:
        return_data["error_message"] = "Invalid Password"
        JsonResponse(return_data)
        # return HttpResponse('Wrong password')
    elif validation.is_valid_email(r_email) is False:
        return_data["error_message"] = "Invalid Email"
        JsonResponse(return_data)
        # return HttpResponse('Email is Invalid')

    return JsonResponse(return_data)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.nodes.get(uid=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.user_type = 1
        user.save_without_encrypt()
        # login(request, user)
        messages.success(request, "Thank you for your email confirmation. Now you can login your account.")
        return HttpResponseRedirect(reverse('homepage:index'))
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


def login(request):

    if request.method == 'POST':
        try:
            username = request.POST.get('username').lower()
            password = request.POST.get('password')
            data = {}
            if username != '' and password != '':
                user = get_user_by_username(username)
                if user is not None:
                    # user = authenticate(username=username, password=password)
                    if pbkdf2_sha256.verify(password, user.password):
                        if user.user_type == 1 or user.user_type == 0:
                            if user.is_active:
                                request.session.set_expiry(7200)  # sets the exp. value of the session
                                request.session['uid'] = user.uid
                                data['error_message'] = 'Success'
                            else:
                                print(user.is_active)
                        else:
                            print(user.user_type)
                        # return HttpResponseRedirect(reverse('homepage:index'), {"uid": user.uid})
                    else:
                        print(pbkdf2_sha256.verify(password, user.password))
                        data['error_message'] = 'Username or Password is not correct. Please try again!'
                        # return JsonResponse(data)
                elif user is None:
                    data['error_message'] = 'Username or Password is not correct. Please try again!'
                    # return JsonResponse(data)
            else:
                data['error_message'] = 'Username and password must be filled'
                # return JsonResponse(data)
            return JsonResponse(data)
        except Exception as e:
            logging.getLogger("error_logger").error("login. " + repr(e))
            return HttpResponseRedirect(reverse('homepage:index'))

    else:
        return HttpResponseRedirect(reverse('homepage:index'))


def check_login(request):#check username is registered or not

    if request.method == "GET":
        raise Http404("URL doesn't exists")
    else:
        response_data = {}
        signup = request.POST["signup"]
        user = None
        try:
            try:
                user = get_user_by_username(username=signup)
            except ObjectDoesNotExist as e:
                pass
            except Exception as e:

dreamers_mas/homepage/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

    Thanks for your registration. Please click on the link below to confirm your e-mail then log in to start discovering our MAS.

https://dreamers-mas.com{% url 'homepage:activate' uidb64=uid token=token %}
{#http://{{ domain }}{% url 'homepage:activate' uidb64=uid token=token %}#}
{% endautoescape %}

dreamers_mas/homepage/templates/after_register_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="refresh" content="10;url={% url 'homepage:index' %}" />
    <!-- Favicon icon -->
{#    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">#}
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/logo2.png' %}">
    <title>The Dreamers</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/lib/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:** -->
    <!--[if lt IE 9]>
    <script src=" {% static 'https:**oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src=" {% static 'https:**oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %}"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar">
    <!-- Preloader - style you can find in spinners.css -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
			<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- Main wrapper  -->
    <div class="error-page" id="wrapper">
        <div class="error-box">
            <div class="error-body text-center">
{#                <h1>400</h1>#}
                <h1> <img src="{% static 'assets/images/logo2.png' %}" style="width: 20%;"/></h1>
{#                <h3 class="text-uppercase" style="color: green;font-weight: bold">Registration is successfully!! </h3>#}

                <h4  style="color: green;">Please access your e-mail to confirm your account.</h4>
                <a class="btn btn-info btn-rounded waves-effect waves-light m-b-40" href="{% url 'homepage:index' %}">Back to home</a> </div>
            <footer class="footer text-center">&copy; 2018 The Dreamers.</footer>
        </div>

    </div>
    <!-- End Wrapper -->
    <!-- All Jquery -->
    <script src=" {% static 'js/lib/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src=" {% static 'js/lib/bootstrap/js/popper.min.js' %}"></script>
    <script src=" {% static 'js/lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src=" {% static 'js/jquery.slimscroll.js' %}"></script>
    <!--Menu sidebar -->
    <script src=" {% static 'js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src=" {% static 'js/lib/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src=" {% static 'js/scripts.js' %}"></script>


</body>

</html>

dreamers_mas/homepage/templates/after_request_change_password.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="refresh" content="10;url={% url 'homepage:index' %}" />
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <title>MAS</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/lib/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:** -->
    <!--[if lt IE 9]>
    <script src=" {% static 'https:**oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src=" {% static 'https:**oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %}"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar">
    <!-- Preloader - style you can find in spinners.css -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
			<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- Main wrapper  -->
    <div class="error-page" id="wrapper">
        <div class="error-box">
            <div class="error-body text-center">
{#                <h1>400</h1>#}
                <h1> <img src="{% static 'assets/images/logo2.png' %}" style="width: 20%;"/></h1>
{#                <h3 class="text-uppercase" style="color: green;font-weight: bold">Registration is successfully!! </h3>#}

                <h4  style="color: green;">Please access your e-mail to change the password.</h4>
                <a class="btn btn-info btn-rounded waves-effect waves-light m-b-40" href="{% url 'homepage:index' %}">Back to home</a> </div>
            <footer class="footer text-center">&copy; 2018 The Dreamers.</footer>
        </div>

    </div>
    <!-- End Wrapper -->
    <!-- All Jquery -->
    <script src=" {% static 'js/lib/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src=" {% static 'js/lib/bootstrap/js/popper.min.js' %}"></script>
    <script src=" {% static 'js/lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src=" {% static 'js/jquery.slimscroll.js' %}"></script>
    <!--Menu sidebar -->
    <script src=" {% static 'js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src=" {% static 'js/lib/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src=" {% static 'js/scripts.js' %}"></script>


</body>

</html>

dreamers_mas/homepage/templates/chane_password.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
{#    <link rel="icon" type="image/png' %}" sizes="16x16" href="{% static 'images/favicon.png' %}">#}
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/logo2.png' %}">
    <title>The Dreamers</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/lib/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/toastr/toastr.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/sweetalert/sweetalert.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:** -->
    <!--[if lt IE 9]>
    <script src="{%  static 'https:**oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="{%  static 'https:**oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %}"></script>
<![endif]-->
    <script>
        $(document).ready(function () {

            $("#pass2").on('change', function () { //compare pass1 and confirm password
                if ($("#pass1").val() == $("#pass2").val()) {
                    $("#not_match").html("<p></p>");
                    {#$('input[id="submit_signup"]').attr("type", "submit");#}
                } else
                    $("#not_match").html("<p class='message' style='color:red'>Password is not Match</p>");
                {#$('input[id="submit_signup"]').attr("type", "button");#}
            });

            var count = 0;
            $("#submit_signup").click (function (e) {

                if ($("#pass1").val() == $("#pass2").val()){


                    {#setTimeout(()=>notification_success("Change password Success!!").present(),5000);#}

                    notification_success("Change password Success!!");

                        {#alert("Change password Success!!");#}
                    {#swal({#}
                    {#    title: "Red Alert!",#}
                    {#    text: "I will close in 213 seconds.",#}
                    {#    timer: 100000,#}
                    {#    showConfirmButton: true,#}
                    {##}
                    {#  });#}

                    {#$(this).unbind('submit').submit();#}



                }

            });

        });

        function check_pass(element) {//Check password from regex in view.py
            signup_password = $(element).val();
            if (signup_password == "") {
                $('input[id="submit_signup"]').attr("type", "button");
                return ;
            }
            $.ajax({
                url: $(element).attr("data-url"),
                data: {
                    "csrfmiddlewaretoken": $(element).siblings("input[name='csrfmiddlewaretoken']").val(),
                    "signup_password": signup_password
                },
                method: "POST",
                dataType: "json",
                success: function (data) {

                    if (data['error_message'] == 'success') {
                        {#$("#email_ok").show();#}

                        $('input[id="submit_signup"]').attr("type", "submit");
                    } else {

                        $("#pass_not").html("<p class='message' style='color:red'>" + data['error_message'] + "</p>");
                        $('input[id="submit_signup"]').attr("type", "button");
                    }
                }
            });

        }

        function clear_pass() {
            $("#pass_not").html("<p></p>")
        }

        function clear_match() {
            $("#not_match").html("<p></p>")
        }
    </script>


</head>

<body class="fix-header fix-sidebar">
<!-- Preloader - style you can find in spinners.css -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
    </svg>
</div>
<!-- Main wrapper  -->
<div id="main-wrapper">

    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-4">
                    <div class="login-content card">
                        <div class="login-form">
                            <h4>Set New Password</h4>
                            <form action="{% url 'homepage:confirm_change_pass' %}" method="POST">
                                {% csrf_token %}
                                <input name="token" value="{{ uid }}" hidden>
                                <div class="form-group">
                                    <label>New Password</label>
                                    <input name="password" id="pass1" class="form-control" type="password"
                                           onkeyup="clear_pass(this)" onblur="check_pass(this);return false"
                                           data-url="{% url 'homepage:check_password' %}" required>
                                    {% csrf_token %}
                                    <div id="pass_not"></div>
                                </div>
                                <div class="form-group">
                                    <label>Confirm New Password</label>
                                    <input name="password2" class="form-control" type="password" id="pass2"
                                           onkeyup="clear_match(this)" required>
                                    <div id="not_match"></div>
                                </div>

                                <input type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" id="submit_signup"
                                       value="Submit">

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- End Wrapper -->
<!-- All Jquery -->
<script src="{% static 'js/lib/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="{% static 'js/lib/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'js/lib/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="{% static 'js/jquery.slimscroll.js' %}"></script>
<!--Menu sidebar -->
<script src="{% static 'js/sidebarmenu.js' %}"></script>
<!--stickey kit -->
<script src="{% static 'js/lib/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
<!--Custom JavaScript -->
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/lib/toastr/toastr.min.js' %}"></script>
<!-- scripit init-->
<script src="{% static 'js/lib/toastr/toastr.init.js' %}"></script>
<script src="{% static 'js/lib/sweetalert/sweetalert.min.js' %}"></script>
    <!-- scripit init-->
<script src="{% static 'js/lib/sweetalert/sweetalert.init.js' %}"></script>


</body>

</html>

dreamers_mas/homepage/templates/reset_password.html
{% autoescape off %}
Hi {{ user.username }},

    Please click to the link below to reset your password.
https://dreamers-mas.com{% url 'homepage:change_password' uidb64=uid token=token %}
{% endautoescape %}